### ISSUE TITLE
Test on OSX and linux in different CI tools

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/sox-bin#4]
I currently have two branches so that I get two badges. I think it is silly to have 2 branches.

Now that [Travis CI supports macos](https://github.com/travis-ci/travis-ci/issues/2311) maybe I can get rid of the extra branch.

Unfortunately, [travis is not implementing a badge for each os](https://github.com/travis-ci/travis-ci/issues/4623) but I can fake it by using yet another build tool.

- [Travis CI](https://travis-ci.org) for macos
- [Circle CI](https://circleci.com/) for linux
- [AppVeyor](https://www.appveyor.com) for windows

**Comment by ArtskydJ** [comment]
```yml
language: node_js
node_js:
- '0.10'
- '0.12'
- '4.0'
- '5.0'
os:
- linux
- osx
matrix:
  fast_finish: true
```
